<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleChat\SimpleChat.csproj" />
  </ItemGroup>

  <ItemGroup>
  	<None Update="startup.json">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  	</None>
  </ItemGroup>

  <ItemGroup>
  	<None Update="peers.json">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  	</None>
  </ItemGroup>

</Project>
